// Les nouveaux textes distinguent les repères documentés de l'évocation personnelle.
export const COLLECTIONS=[
 {slug:'le-mercredi-apres-midi',title:'Le mercredi après-midi',short:'Jeux, dessins animés, copains et liberté.',intro:'Le cartable attendra. Une manette, un générique, un copain qui sonne : l’après-midi avait déjà trouvé son programme.',image:'mercredi',alt:'Une PlayStation grise et sa manette dans une chambre chaleureuse, scène reconstituée.',slugs:['club-dorothee','game-boy','mega-drive','super-nintendo','playstation','dragon-ball-z','les-pogs','tamagotchi']},
 {slug:'la-soiree-video-club',title:'La soirée vidéo-club',short:'Choisir, hésiter, repartir avec des étoiles plein la tête.',intro:'On venait chercher un film. On restait pour les jaquettes, les hésitations et cette négociation interminable devant le rayon nouveautés.',image:'videoclub',alt:'Une façade de vidéo-club à la nuit tombée, scène reconstituée.',slugs:['jurassic-park','retour-vers-le-futur','la-jaquette-fait-le-film','rembobiner-avant-de-rendre','le-film-deja-loue','le-magnetoscope','le-dimanche-20h45']},
 {slug:'le-gouter-de-16h30',title:'Le goûter de 16h30',short:'Un petit réconfort après l’école. Tout un rituel.',intro:'Le bruit du paquet, le verre posé sur la table, la première bouchée. Le goûter n’avait pas besoin d’être extraordinaire pour devenir inoubliable.',image:'gouter',alt:'Biscuit souriant, lait et tartine dans une cuisine ensoleillée, scène reconstituée.',slugs:['pitch-contre-choco-bn','carambar','malabar','tang-nesquik','yop-danette-flanby','champomy','chocapic-frosties-tresor','pom-potes']}
];
const nintendo=['Nintendo, histoire de la marque','https://www.nintendo.com/en-gb/Hardware/Nintendo-History/Nintendo-History-625945.html','Repères de commercialisation par période et par territoire.'];
export const EDITORIAL={
 'playstation':{
  d:'Un disque noir, un démarrage qui résonne encore et une carte mémoire qu’il ne fallait surtout pas perdre. La PlayStation a changé nos mercredis.',
  summary:'La première PlayStation de Sony sort au Japon le 3 décembre 1994, puis en Europe le 29 septembre 1995. Ses jeux sur CD, ses univers en 3D et sa bibliothèque très variée en font l’un des objets marquants de la seconde moitié des années 90.',
  question:'Le jeu que tu relancerais ce soir, sans même regarder la jaquette, ce serait lequel ?',
  sources:[['Sony, l’histoire de la première PlayStation','https://www.playstation.com/fr-fr/playstation-history/1994-ps-one/','Dates de lancement, modèles et évolution des manettes.']],
  doc:{q:'playstation tekken tomb raider ridge racer',art:[
   {t:'Ce son voulait dire que la soirée commençait',p:['On appuyait sur le bouton. Un son grave remplissait le salon, le logo apparaissait, puis on attendait. Ces quelques secondes faisaient déjà partie du jeu. Même quand on avait lancé la même console cent fois, elles conservaient quelque chose d’un petit départ.','La PlayStation, c’était aussi une place à négocier dans la maison : le câble devant le meuble, les boîtiers près de la télévision, et quelqu’un qui demandait si ça allait durer longtemps. Réponse officielle : pas longtemps. Réponse réelle : on préférait ne pas s’engager.']},
   {t:'La 3D, pas encore lisse, déjà immense',p:['Les mondes avaient des angles, les visages peu de détails et certaines caméras leur propre opinion sur la direction à prendre. Cela n’empêchait pas d’avoir l’impression d’entrer dans un espace nouveau. Le plaisir venait autant de l’exploration que de la maîtrise.','Dans les souvenirs, les jeux se mélangent parfois aux personnes avec qui on les découvrait. Une course regardée par-dessus l’épaule, un combat dont on contestait les règles, une énigme résolue à deux. La console était un objet individuel qui créait volontiers une petite assemblée.']},
   {t:'Le CD et la petite carte à ne pas oublier',p:['Le disque se rangeait dans sa boîte, idéalement. Dans la pratique, une pochette vide ne signifiait pas que le jeu avait disparu : il pouvait être dans une autre boîte, ou chez le copain qui jurait l’avoir rendu.','La carte mémoire, elle, contenait une autre sorte de valeur. La progression, les personnages, les heures passées. Avant de commencer, on vérifiait parfois qu’il restait de la place. Et avant d’effacer une sauvegarde, on apprenait à demander à qui elle appartenait. Voilà une première formation très concrète à la vie en communauté.']},
   {t:'La manette a changé pendant la décennie',p:['Attention au souvenir qui rassemble toutes les versions dans une seule image : la manette d’origine n’avait pas les deux sticks analogiques du DualShock. Sony a fait évoluer les commandes au fil de la vie de la console.','La photographie de ce dossier montre une PlayStation grise accompagnée d’une manette DualShock. Elle illustre un ensemble reconnaissable de la fin des années 90, pas le contenu exact de toutes les boîtes vendues au lancement. La petite PS one blanche, elle, appartient à l’année 2000.']},
   {t:'La revoir aujourd’hui, sans tricher avec la mémoire',p:['Un téléviseur moderne ne restitue pas exactement l’image d’un tube cathodique. La taille de l’écran, le traitement de l’image et la façon dont on s’installe changent la perception. Le souvenir conserve souvent la sensation du jeu davantage que ses pixels.','C’est aussi pour cela qu’on aime revoir les archives : elles remettent les publicités, les présentations et les images dans leur époque. Avec un peu de recul, mais sans se moquer des joueurs que nous étions. Après tout, ils avaient de très bonnes raisons d’être impressionnés.']}],specs:{t:'Les repères, sans rembobiner de travers',l:[['Fabricant','Sony'],['Japon','3 décembre 1994'],['Europe','29 septembre 1995'],['Support des jeux','CD-ROM'],['Modèle photographié','PlayStation grise avec DualShock'],['À distinguer','PS one, version compacte sortie en 2000']]},plus:['Le bon souvenir n’est pas forcément celui du jeu le plus célèbre. Parfois, c’est simplement celui auquel on jouait ensemble.','Les étiquettes des cartes mémoire étaient un minuscule territoire privé : un prénom, un dessin, parfois un avertissement très clair.']}
 },
 'tamagotchi':{
  d:'Trois boutons, un petit écran et une créature qui n’avait visiblement pas consulté ton emploi du temps. Retour sur le plus exigeant des porte-clés.',
  summary:'Le Tamagotchi est un animal virtuel de poche créé par Bandai. Lancé au Japon le 23 novembre 1996 puis diffusé à l’international en 1997, il demande des soins réguliers : nourriture, jeu, nettoyage et attention.',
  sources:[['Bandai, présentation historique de Tamagotchi','https://www.bandai.co.jp/character/tamagotchi.php','Date du lancement japonais.'],['Bandai, Original Tamagotchi','https://www.bandai.com/brands/tamagotchi/original-tamagotchi','Les rééditions reprennent la programmation des premiers modèles internationaux.']],
  question:'Tu en prenais soin comme d’un trésor, ou tu le confiais à quelqu’un au bout de deux jours ?',
  doc:{q:'tamagotchi bandai',art:[
   {t:'Un animal qui tenait dans la poche',p:['Il n’avait ni fourrure ni grand discours. Quelques pixels suffisaient pour qu’on surveille son humeur et qu’on se sente responsable. L’œuf en plastique pouvait être accroché à un sac, rangé dans une poche ou posé à côté du cahier. Il trouvait toujours le moyen de rester dans un coin de la tête.','L’objet renversait une habitude : on ne jouait plus seulement quand on l’avait décidé. La petite créature avait ses besoins et son rythme. Un bip, et l’attention repartait vers elle. L’idée avait quelque chose de drôle, de tendre, et parfois d’un peu encombrant.']},
   {t:'Trois boutons, beaucoup de responsabilités',p:['Les actions passent par des icônes et un menu très simple. On nourrit l’animal, on joue, on nettoie et on surveille ses indicateurs. La difficulté n’est pas de comprendre un mode d’emploi de cinquante pages. C’est de ne pas oublier le petit être quand la vraie vie appelle.','Ce décalage donne au jouet sa personnalité. Il peut réclamer de l’attention au moment où l’on doit partir, manger ou se concentrer. Dans les souvenirs d’école, la peur du bip et celle de la confiscation font presque partie de la fiche technique. Ce sont des expériences racontées par les joueurs, pas une statistique sur toutes les cours de récré.']},
   {t:'Le compagnon qu’on compare avec celui des autres',p:['On ne comparait pas seulement les couleurs des coques. On regardait la créature obtenue, son âge, son état. Le jouet personnel devenait très vite un sujet collectif. Et l’on échangeait des conseils avec l’assurance de spécialistes qui possédaient leur premier animal numérique depuis le mardi précédent.','Les astuces circulaient plus vite que les notices. Certaines dépendaient du modèle, d’autres étaient simplement des légendes. Plutôt que de les transformer en vérités universelles, mieux vaut distinguer ce que le jouet permet vraiment et ce qu’on se racontait autour de lui.']},
   {t:'Original, réédition et autres animaux virtuels',p:['Tous les petits animaux électroniques de l’époque ne sont pas des Tamagotchi Bandai. D’autres fabricants ont proposé leurs propres compagnons, avec des formes et des règles différentes. Leur ressemblance ne suffit pas à en faire des contrefaçons.','Il existe aussi des rééditions officielles. Elles peuvent reprendre l’allure d’origine sans être des exemplaires fabriqués en 1997. Pour identifier un objet de collection, les inscriptions, le modèle, la coque et la provenance sont plus utiles que la seule couleur. La photo d’un dossier doit aider à reconnaître l’objet, pas brouiller ces différences.']},
   {t:'Pourquoi on s’en souvient si bien',p:['Parce que la relation était minuscule, mais personnelle. Le jouet ne proposait pas un immense monde à explorer : il installait un rendez-vous dans la journée. Et parfois un peu de culpabilité, logée entre deux boutons.','Le revoir, c’est retrouver ce mélange très particulier de fierté et d’inquiétude. On riait de prendre autant soin d’un écran. Puis on allait quand même vérifier s’il n’avait pas faim.']}],specs:{t:'Le bon modèle, les bons repères',l:[['Marque','Bandai'],['Lancement au Japon','23 novembre 1996'],['Diffusion internationale','1997'],['Principe','Un animal virtuel dont on s’occupe'],['À identifier sur une photo','Modèle, génération et éventuelle réédition']]},plus:['Le mot Tamagotchi désigne une marque et une famille de jouets : les règles ne sont pas identiques sur toutes les générations.','Le souvenir du bip est parfois plus précis que celui de la couleur de la coque. La mémoire a ses priorités.']}
 },
 'game-boy':{
  d:'Une brique grise, un écran verdâtre et l’incroyable pouvoir de raccourcir les trajets. La Game Boy n’avait pas besoin de couleurs pour remplir nos journées.',
  sources:[['Nintendo, Game Boy','https://www.nintendo.com/fr-fr/Hardware/L-histoire-de-Nintendo/Game-Boy/Game-Boy-627031.html','Présentation de la console originale.'],nintendo],
  summary:'La Game Boy originale est la console portable de Nintendo lancée au Japon en 1989 et en Europe en 1990. Son écran monochrome et ses cartouches en font un compagnon emblématique des années 90. Elle est différente de la Game Boy Color, arrivée plus tard.',
  doc:{q:'game boy nintendo',art:[
   {t:'Le monde rentrait dans une cartouche',p:['Un interrupteur, un petit écran, deux boutons et la croix directionnelle. L’objet avait une simplicité rassurante : pas besoin de monopoliser la télévision du salon pour commencer une partie. On emportait son jeu avec soi.','Le vrai luxe, c’était cette autonomie de décision. Jouer dans sa chambre, chez un cousin ou pendant une attente. À condition d’avoir des piles, évidemment. Le mot « portable » n’avait jamais promis de les faire apparaître.']},
   {t:'L’écran avait ses exigences',p:['L’image monochrome faisait partie de son identité. On cherchait la bonne lumière, on modifiait l’inclinaison, on ajustait le contraste. Ce petit cérémonial précédait parfois la partie sans qu’on y pense.','La Game Boy originale n’offre pas le confort lumineux d’un écran de téléphone. Le souvenir reste pourtant généreux : une petite surface suffisait pour rendre un niveau immense et une défaite particulièrement agaçante.']},
   {t:'Prêter une cartouche, c’était prêter une aventure',p:['Les échanges faisaient vivre la console au-delà de sa propre boîte de jeux. Une cartouche passait d’une maison à l’autre, accompagnée de conseils et de promesses de restitution. On connaissait parfois un passage difficile avant même d’avoir vu le jeu.','À deux, certains jeux utilisaient le câble de liaison. Le câble était un accessoire concret qu’il fallait avoir sous la main, pas une fonctionnalité invisible. Le préparer faisait déjà partie du rendez-vous.']},
   {t:'Ne pas confondre toutes les Game Boy',p:['La brique grise photographiée ici correspond à la silhouette de la première Game Boy. Nintendo a ensuite fait évoluer la famille, notamment avec la Pocket et la Color. Elles partagent une histoire, mais pas exactement le même boîtier, le même écran ni toutes les compatibilités.','Une photographie précise vaut mieux qu’une image approximative de « console rétro ». Les deux boutons bordeaux, la croix noire et la forme de l’écran ne sont pas un décor interchangeable : ils font partie de ce qu’on reconnaît immédiatement.']},
   {t:'Le trajet était trop court, finalement',p:['Ce qui revient n’est pas toujours un score. Cela peut être la position au fond de la voiture, le bruit d’un bouton, ou quelqu’un qui demande de baisser le son. Le jeu s’est accroché à un lieu et à un moment.','Alors oui, les écrans ont changé. Mais cette façon de sortir une petite console de son sac et de se fabriquer une parenthèse reste une idée franchement réussie.']}],specs:{t:'La console originale',l:[['Fabricant','Nintendo'],['Japon','1989'],['Europe','1990'],['Écran','Monochrome'],['Support','Cartouches'],['À distinguer','Game Boy Pocket et Game Boy Color']]},plus:['Une boîte de cartouche vide pouvait déclencher une enquête familiale tout à fait disproportionnée.','La meilleure lumière n’était pas toujours à la meilleure place pour s’asseoir.']}
 },
 'mega-drive':{sources:[['SEGA, histoire officielle','https://www.sega.jp/history/companyTimeline/en/','Lancement japonais en 1988, nord-américain en 1989 sous le nom Genesis et européen en 1990.']],summary:'La Mega Drive est une console de salon de SEGA, lancée au Japon en 1988 puis en Europe en 1990. Connue sous le nom Genesis en Amérique du Nord, elle incarne en France une partie des grandes rivalités vidéoludiques des années 90.'},
 'super-nintendo':{sources:[nintendo],summary:'La Super Nintendo est la version occidentale de la Super Famicom japonaise. Elle arrive en Europe en 1992 et compte parmi les consoles de salon majeures des années 90. La version PAL photographiée ici se reconnaît notamment à ses boutons de manette colorés.'},
 'nintendo-64':{sources:[nintendo],summary:'La Nintendo 64 est la console de Nintendo associée au passage de ses grandes séries à la 3D. Commercialisée en Europe en 1997, elle conserve les cartouches et dispose de quatre ports manette.'},
 'le-walkman':{sources:[['Sony, vingt ans de Walkman','https://www.sony.com/en/SonyInfo/News/Press/199907/99-059/','Communiqué de 1999 : premier TPS-L2 en juillet 1979 et évolution des baladeurs.'],['Sony Design, les générations de Walkman','https://www.sony.com/en/SonyInfo/design/bside/01_throwback_walkman/','Repères visuels pour distinguer les modèles.']],summary:'Walkman est la marque de baladeurs de Sony, née avec le TPS-L2 en 1979. Dans les années 90, les baladeurs à cassette accompagnent les trajets et les compilations personnelles. Le modèle photographié ici est le pionnier de 1979, pas un modèle lancé en 1994.'},
 'le-minitel':{sources:[['Orange, histoire du groupe et du Minitel','https://www.orange.com/en/our-groupe/our-history','Repère du développement du Minitel à partir de 1982.']],summary:'Le Minitel est un terminal d’accès aux services télématiques français, déployé à partir des années 80. Annuaire, informations et messageries passent par la ligne téléphonique. Il précède le Web dans de nombreux foyers, sans être pour autant Internet.'},
 'club-dorothee':{
  d:'Il suffisait de quelques notes pour que le salon change de programme. Dessins animés, chansons, copains de télévision : retour sur un rendez-vous à part.',
  summary:'Le Club Dorothée est un programme jeunesse diffusé sur TF1 de 1987 à 1997. Animé par Dorothée et son équipe, il rassemble émissions de plateau, dessins animés, chansons et séries. Les années 90 constituent le cœur de son empreinte dans les souvenirs de nombreux téléspectateurs.',
  sources:[['INA, notice du Club Dorothée','https://catalogue.ina.fr/doc/TV-RADIO/TV_437312.001/club-dorothee','Période de diffusion sur TF1 et description de l’émission.']],
  doc:{q:'club dorothee',art:[
   {t:'Un rendez-vous qui ressemblait à une bande de copains',p:['Le souvenir commence souvent avant le dessin animé. Il y a une voix, une chanson, quelqu’un sur le plateau que l’on reconnaît immédiatement. Le Club Dorothée installait cette familiarité : une équipe retrouvée, des habitudes, la sensation de reprendre une conversation commencée la veille.','Ce n’était pas la même place dans toutes les familles. Télévision très présente chez les uns, rendez-vous négocié chez les autres, programme découvert chez un copain. Les souvenirs n’ont pas besoin d’être identiques pour se répondre.']},
   {t:'Une émission autour des programmes',p:['Il faut distinguer le Club Dorothée des séries et dessins animés qu’il diffusait. L’émission constituait un cadre, un rendez-vous et une manière de présenter les programmes. Chaque série avait ensuite sa propre histoire, sa production et ses dates d’arrivée.','Cette distinction évite de faire commencer tous les dessins animés la même année, ou d’attribuer à l’émission la création de leurs personnages. La nostalgie fait facilement un grand paquet. Les dossiers sont là pour le déplier sans lui retirer son plaisir.']},
   {t:'Le générique est une mémoire très efficace',p:['On peut oublier une intrigue et retrouver instantanément l’énergie d’un générique. Quelques images, une mélodie, un rythme : le cerveau semble savoir exactement où les ranger. Et parfois il conserve le refrain avec une précision peu utilisée pour les tables de multiplication.','Revoir une archive permet aussi de retrouver des détails moins attendus : une transition, un décor de plateau, la façon de parler à la caméra. Ce sont ces petits éléments qui rendent le document plus intéressant qu’un simple titre dans une liste.']},
   {t:'La fin d’un rendez-vous, pas celle du souvenir',p:['L’émission s’arrête en 1997. Les enfants continuent à grandir, les habitudes de télévision changent, et les souvenirs suivent chacun leur chemin. Certains programmes restent aimés, d’autres se regardent aujourd’hui avec davantage de recul.','Un hommage n’oblige pas à tout idéaliser. Il peut retrouver la joie du rendez-vous tout en replaçant les images dans leur époque. On a le droit de sourire du décor et d’être ému par la musique dans la même minute.']},
   {t:'Par où commencer les archives ?',p:['Les génériques associés à ce dossier sont une bonne porte d’entrée. Regarde aussi leur habillage, les noms et la provenance de la vidéo. Une version de générique ne résume pas les dix années du programme.','Puis suis le fil : un dessin animé, une chanson, une émission voisine. C’est souvent de cette manière que la mémoire fonctionne, un souvenir ouvrant la porte au suivant. Et soudain, la pause de deux minutes dure un peu plus longtemps.']}],specs:{t:'Les repères du rendez-vous',l:[['Chaîne','TF1'],['Période','1987 à 1997'],['Nature','Programme jeunesse avec animation de plateau'],['À distinguer','L’émission et les œuvres qu’elle diffusait']]},plus:['La provenance d’une archive compte : elle aide à distinguer un document d’époque, un montage de fan et un habillage recréé.']}
 },
 'jurassic-park':{
  t:'Jurassic Park',p:'cine.html',cat:'cine',y:'1993',d:'On voulait visiter le parc. Puis on a vu la cuisine. Retour sur le film qui a donné un poids, un souffle et une sacrée présence aux dinosaures.',videoIds:['UGl2o7TfHmU'],
  summary:'Jurassic Park est un film de Steven Spielberg sorti en 1993, adapté du roman de Michael Crichton. Ses dinosaures combinent créations animatroniques et images numériques. Son histoire nous fait passer de l’émerveillement à la peur, parfois sans quitter le même siège.',
  sources:[['Amblin, Jurassic Park','https://amblin.com/movie/jurassic-park/','Film, équipe artistique et combinaison des effets physiques et numériques.']],
  question:'Ta première rencontre avec le T. rex : au cinéma, devant une VHS, ou un soir à la télévision ?',
  doc:{q:'jurassic park',art:[
   {t:'D’abord, on avait envie d’y croire',p:['Avant la peur, il y a l’émerveillement. La première découverte du parc fonctionne comme une invitation : regarde la taille, le mouvement, l’espace que prennent ces animaux. Le film nous laisse partager l’étonnement des personnages. On sait que l’on regarde du cinéma. On a quand même très envie d’oublier ce détail.','Cette première émotion compte. Si la suite inquiète autant, c’est aussi parce qu’on avait accepté la promesse du lieu. Le parc ressemblait à un rêve d’enfant auquel on aurait enfin ajouté une billetterie. Mauvaise idée commerciale, excellent point de départ pour un film.']},
   {t:'Le numérique n’a pas tout fait tout seul',p:['La force des dinosaures vient notamment de l’association de techniques différentes. Des créatures animatroniques conçues par l’équipe de Stan Winston apportent une présence physique, tandis que les images de synthèse permettent d’autres mouvements et plans.','Plutôt que de réduire le film à « l’arrivée des ordinateurs », il est plus juste de regarder cette complémentarité. La lumière, le montage, le son et la mise en scène travaillent ensemble. Un animal qui paraît réel, ce n’est pas seulement une image détaillée : c’est aussi une présence à laquelle tout le plan réagit.']},
   {t:'L’attente, ce terrible effet spécial',p:['Dans les scènes de tension, le film sait laisser le temps s’étirer. Un bruit, un regard, un mouvement aperçu : notre imagination prend de l’avance. Et elle ne propose généralement pas le scénario le plus rassurant.','Le revoir adulte ne supprime pas forcément cette mécanique. On connaît le danger, mais on retrouve le rythme qui le rend menaçant. C’est un des plaisirs du revisionnage : observer comment le film obtient un effet que l’on ressent encore.']},
   {t:'Du cinéma au salon, le souvenir change de taille',p:['Certains ont découvert les dinosaures sur grand écran. D’autres à travers la jaquette d’une cassette, puis sur la télévision familiale. Le contexte change le souvenir : la salle, la personne assise à côté, le volume que l’on baissait pour se rassurer.','La VHS ajoute son propre rituel. Choisir le film, installer la cassette, espérer qu’elle soit rembobinée. Un grand spectacle pouvait devenir un objet que l’on rapportait dans un sac. Et que l’on voulait souvent garder un jour de plus.']},
   {t:'Un classique à regarder avec deux regards',p:['On peut revenir au film pour les sensations de la première fois et, en même temps, regarder davantage les détails de fabrication. Ces deux façons de le voir ne se contredisent pas. Elles se complètent.','La bande-annonce proposée ici permet de retrouver sa présentation et son imaginaire sans prétendre remplacer le long métrage. Pour raconter ton premier visionnage, direction le Club : les souvenirs de siège de cinéma valent parfois autant que ceux des dinosaures.']}],specs:{t:'Le film en quelques repères',l:[['Réalisation','Steven Spielberg'],['Année','1993'],['Origine','Roman de Michael Crichton'],['Production','Amblin Entertainment'],['Dinosaures','Association d’animatroniques et d’images numériques']]},plus:['Les images du film ne constituent pas un document scientifique sur tous les dinosaures : elles appartiennent aussi aux choix et aux connaissances de leur époque.','Le meilleur compagnon de revisionnage est parfois quelqu’un qui ne l’a encore jamais vu. Prévois simplement de ne pas commenter chaque scène avant qu’elle arrive.']}
 },
 'retour-vers-le-futur':{
  videoIds:['wlovrxHwLxI'],t:'Retour vers le futur',p:'cine.html',cat:'cine',y:'1985, revu dans les années 90',d:'Une DeLorean, un rendez-vous avec l’horloge et un film dont on connaît la fin. Ce qui ne nous empêche absolument pas de retenir notre souffle.',image:'assets/editorial/videoclub.webp',imageAlt:'Une soirée au vidéo-club, ambiance reconstituée.',imageCredit:'Ambiance reconstituée pour RETOUR90, pas une image du film.',
  summary:'Retour vers le futur est le film de Robert Zemeckis sorti en 1985, suivi de deux autres volets en 1989 et 1990. Sa place dans les années 90 tient autant à cette trilogie qu’aux découvertes et revisionnages en VHS et à la télévision.',
  sources:[['Back to the Future, site officiel de la trilogie','https://www.backtothefuture.com/','Films, créateurs et repères de la trilogie.']],
  question:'Si Doc te laissait choisir une seule année, tu lui demanderais laquelle ?',
  doc:{q:'retour futur',art:[
   {t:'Un film de 1985 dans nos souvenirs des années 90',p:['C’est un bon exemple de la différence entre une date de sortie et une date de rencontre. On peut découvrir un film plusieurs années après sa naissance, le revoir sans se lasser et l’associer à une période très précise de sa propre vie.','La cassette louée, le passage à la télévision ou le film regardé chez un cousin deviennent alors le vrai point de départ du souvenir. Ici, on ne déplace pas la sortie du film pour le faire entrer dans une décennie. On raconte pourquoi il y avait encore toute sa place.']},
   {t:'Le voyage dans le temps commence près de chez soi',p:['Le plaisir tient aussi au contraste : une vie quotidienne reconnaissable, puis une machine qui rend possible l’impossible. L’aventure pose une question que chacun peut s’approprier. Que découvrirait-on si l’on rencontrait ses proches avant d’être né ?','Ce n’est plus seulement une histoire de technologie. C’est une façon drôle et parfois vertigineuse de regarder les générations. Les adultes ont eu un âge où ils ne savaient pas encore très bien où ils allaient. Étonnante information quand on a dix ans.']},
   {t:'Revoir, c’est repérer ce qui prépare la suite',p:['Une fois l’histoire connue, on observe autrement les objets et les détails. Ce qui paraissait anodin peut devenir un indice, un rappel ou une préparation. Le film se prête particulièrement bien à ce plaisir de reconnaissance.','On peut aussi simplement se laisser embarquer. Il n’existe aucune obligation de transformer chaque séance en commentaire de scénario. Parfois, le meilleur programme consiste à s’installer et à attendre son passage préféré avec un sourire un peu idiot.']},
   {t:'La trilogie et la cassette qu’on connaissait par cœur',p:['Les trois films ne datent pas tous des années 90 : le premier est de 1985, le deuxième de 1989 et le troisième de 1990. Les regrouper dans nos souvenirs ne doit pas effacer cette chronologie.','À la maison, les habitudes de revisionnage fabriquaient une autre organisation. Le volet préféré, celui qu’on possédait, celui qu’on avait enregistré. Une collection de cassettes dépendait aussi de ce qui était disponible, pas seulement d’un classement de cinéphile.']},
   {t:'Le vrai voyage, celui du spectateur',p:['Revoir le même film à différents âges fait apparaître d’autres choses. Une scène surtout amusante peut devenir touchante. Un personnage que l’on regardait peu attire davantage l’attention. Le film ne change pas ; la place depuis laquelle on le regarde, si.','C’est peut-être ce qui le relie si bien à RETOUR90. On ne cherche pas seulement à retrouver une image intacte. On veut aussi voir ce qu’elle réveille aujourd’hui, et le raconter à quelqu’un qui se souvient autrement.']}],specs:{t:'La chronologie à garder en tête',l:[['Premier film','1985'],['Deuxième volet','1989'],['Troisième volet','1990'],['Réalisation','Robert Zemeckis'],['Dans RETOUR90','Un film retrouvé et revu pendant la décennie']]},plus:['La DeLorean est un véritable modèle automobile, transformé pour les besoins de la fiction. Une voiture de série et sa version de cinéma ne sont pas interchangeables.']}
 }
};
